package:
  name: networkit
  version: !!str 3.4.1

source:
  fn: networkit-3.4.1.tar.gz
  url: https://pypi.python.org/packages/source/n/networkit/networkit-3.4.1.tar.gz
  md5: e1a96fb18660cd359bbd0c97135ff793
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - networkit = networkit:main
    #
    # Would create an entry point called networkit that calls networkit.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - scipy

  run:
    - python
    - networkx
    - scipy
    - tabulate
    - matplotlib
    - seaborn
    - pandas

test:
  # Python imports
  imports:
    - networkit
    - networkit.gephi
    - networkit.test
    - networkit.test.extension
    - networkit.test.gephi
    - networkit.viztools

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://networkit.iti.kit.edu/
  license: MIT License
  summary: 'NetworKit is a toolbox for high-performance network analysis'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
