{% set name = "petsc" %}
{% set version = "3.7.3" %}
{% set sha256 = "7509281536ab7b908ee77ce5e999bb196f1a9e6ac5515f4518e1c3331e27128a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-lite-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/{{ name }}-lite-{{ version }}.tar.gz # [not win]
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python 2.*  # configure requires python 2
    - mkl-rt 11.1
  run:
    - mkl-rt 11.1

test:
  requires:
    - python 3.4.*  # [py34]
    - python 3.5.*  # [py35]

about:
  home: http://www.mcs.anl.gov/petsc/
  license: Public Domain
