package:
  name: petsc
  version: 3.6.1

source:
  fn: petsc-lite-3.6.1.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.6.1.tar.gz # [linux]
  md5: 907c01021d61d879c9db17f93afd3461

build:
  number: 0
  features:
    - mkl

requirements:
  build:
    - python
    - mkl-rt 11.1*
  run:
    - mkl-rt 11.1*

test:
  requires:
    - mkl-rt 11.1*

about:
  home: http://www.mcs.anl.gov/petsc/
  license: Public Domain
