package:
  name: petsc
  version: 3.5.2

source:
  fn: petsc-lite-3.5.2.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.5.2.tar.gz # [linux]
  md5: d707336a98d7cb31d843804d020edc94

build:
  number: 2
  features:
    - mkl

requirements:
  build:
    - python
    - mkl-rt 11.1*
  run:
    - mkl-rt 11.1*

test:
  requires:
    - mkl-rt 11.1*

about:
  home: http://www.mcs.anl.gov/petsc/
  license: Public Domain
