{% set name = "slepc4py" %}
{% set version = "3.7.0" %}
{% set sha256 = "5836334ec62f007b0e527c3d63577a43fee3c870c80df23256c55521ad6f4cc6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/slepc/slepc4py/downloads/{{ name }}-{{ version }}.tar.gz # [not win]
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python {{PY_VER}}*
    - numpy x.x
    - slepc
    - petsc4py
  run:
    - python {{PY_VER}}*
    - numpy x.x
    - slepc
    - petsc4py

test:
  requires:
    - petsc4py

  imports:
    - slepc4py
    - slepc4py.SLEPc

about:
  home: https://bitbucket.org/slepc/slepc4py/
  license:  BSD
