package:
  name: slepc4py
  version: 3.6.0

source:
  fn: slepc4py-3.6.0.tar.gz
  url: https://bitbucket.org/slepc/slepc4py/downloads/slepc4py-3.6.0.tar.gz # [linux]
  md5: 3d4c163dc482438684cdaa485ebf37fd

build:
  number: 0
  features:
    - mkl

requirements:
  build:
    - python
    - numpy 1.9*
    - slepc
    - mkl
    - petsc4py
  run:
    - python
    - numpy 1.9*
    - slepc
    - mkl
    - petsc4py

test:
  requires:
    - mkl
    - petsc4py
    - slepc

  imports:
    - slepc4py
    - slepc4py.SLEPc

about:
  home: https://bitbucket.org/slepc/slepc4py/
  license:  BSD
