{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rlrsim
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "3.1_3"

source:
  fn: RLRsim_3.1-3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/RLRsim_3.1-3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/RLRsim/RLRsim_3.1-3.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-rcpp >=0.11.1
    - r-lme4 >=1.1
    - r-mgcv
    - r-nlme
    - posix               # [win]
    - {{native}}toolchain # [win]
    - gcc                 # [not win]

  run:
    - r-base
    - r-rcpp >=0.11.1
    - r-lme4 >=1.1
    - r-mgcv
    - r-nlme

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RLRsim')" # [not win]
    - "\"%R%\" -e \"library('RLRsim')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/fabian-s/RLRsim
  license: GPL
  summary: Rapid, simulation-based exact (restricted) likelihood ratio tests for testing the
    presence of variance components/nonparametric terms for models fit with nlme::lme(),lme4::lmer(),
    lmeTest::lmer(), gamm4::gamm4(), mgcv::gamm() and SemiPar::spm().
  license_family: GPL

# The original CRAN metadata for this package was:

# Package: RLRsim
# Type: Package
# Title: Exact (Restricted) Likelihood Ratio Tests for Mixed and Additive Models
# Version: 3.1-3
# Date: 2016-11-03
# Authors@R: c(person("Fabian", "Scheipl", role = c("aut", "cre"), email = "fabian.scheipl@stat.uni-muenchen.de"), person("Ben", "Bolker", role = "aut"))
# Maintainer: Fabian Scheipl <fabian.scheipl@stat.uni-muenchen.de>
# Description: Rapid, simulation-based exact (restricted) likelihood ratio tests for testing the presence of variance components/nonparametric terms for models fit with nlme::lme(),lme4::lmer(), lmeTest::lmer(), gamm4::gamm4(), mgcv::gamm() and SemiPar::spm().
# License: GPL
# URL: https://github.com/fabian-s/RLRsim
# BugReports: https://github.com/fabian-s/RLRsim/issues
# Depends: R (>= 2.14.0)
# Imports: Rcpp (>= 0.11.1), lme4 (>= 1.1), mgcv, nlme
# LinkingTo: Rcpp
# Enhances: SemiPar, lmerTest
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2016-11-04 12:43:10 UTC; fabians
# Author: Fabian Scheipl [aut, cre], Ben Bolker [aut]
# Repository: CRAN
# Date/Publication: 2016-11-04 23:33:58

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
