package:
  name: multiprocess
  version: "0.70.5"

source:
  fn: multiprocess-0.70.5.zip
  url: https://pypi.python.org/packages/65/03/bd8ac79948049b5a0f7ee5f2642f76dbb2d9cb83cc5433dfb2112f89d69a/multiprocess-0.70.5.zip
  md5: bfe394368b1d98192f1f62cc0060be20
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - multiprocess = multiprocess:main
    #
    # Would create an entry point called multiprocess that calls multiprocess.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - dill >=0.2.6

  run:
    - python
    - dill >=0.2.6

test:
  # Python imports
  imports:
    - multiprocess
    - multiprocess.dummy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://developer.berlios.de/projects/pyprocessing
  license: BSD
  summary: 'Package for using processes which mimics the threading module'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
