{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mlmetrics
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.1.1"

source:
  fn: MLmetrics_1.1.1.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/MLmetrics_1.1.1.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/MLmetrics/MLmetrics_1.1.1.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: e1071
requirements:
  build:
    - r-base
    - r-rocr

  run:
    - r-base
    - r-rocr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('MLmetrics')" # [not win]
    - "\"%R%\" -e \"library('MLmetrics')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/yanyachen/MLmetrics
  license: GPL-2
  summary: A collection of evaluation metrics, including loss, score and utility functions, that
    measure regression, classification and ranking performance.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: MLmetrics
# Type: Package
# Title: Machine Learning Evaluation Metrics
# Version: 1.1.1
# Authors@R: person("Yachen", "Yan", email = "yanyachen21@gmail.com", role = c("aut", "cre"))
# Description: A collection of evaluation metrics, including loss, score and utility functions, that measure regression, classification and ranking performance.
# URL: http://github.com/yanyachen/MLmetrics
# BugReports: http://github.com/yanyachen/MLmetrics/issues
# Depends: R (>= 2.10)
# Imports: stats, utils, ROCR
# Suggests: e1071
# License: GPL-2
# LazyData: true
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-05-09 06:13:55 UTC; Administrator
# Author: Yachen Yan [aut, cre]
# Maintainer: Yachen Yan <yanyachen21@gmail.com>
# Repository: CRAN
# Date/Publication: 2016-05-13 23:57:26

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
