{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sgl
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.1"

source:
  fn: SGL_1.1.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/SGL_1.1.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/SGL/SGL_1.1.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - posix               # [win]
    - {{native}}toolchain # [win]
    - gcc                 # [not win]

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('SGL')" # [not win]
    - "\"%R%\" -e \"library('SGL')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL
  summary: Fit a regularized generalized linear model via penalized maximum likelihood.  The
    model is fit for a path of values of the penalty parameter. Fits linear, logistic
    and Cox models.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: SGL
# Type: Package
# Title: Fit a GLM (or cox model) with a combination of lasso and group lasso regularization
# Version: 1.1
# Date: 2010-10-12
# Author: Noah Simon, Jerome Friedman, Trevor Hastie, and Rob Tibshirani
# Maintainer: Noah Simon <nsimon@stanford.edu>
# Description: Fit a regularized generalized linear model via penalized maximum likelihood.  The model is fit for a path of values of the penalty parameter. Fits linear, logistic and Cox models.
# License: GPL
# LazyLoad: yes
# Packaged: 2013-04-02 17:43:37 UTC; nsimon
# Repository: CRAN
# Date/Publication: 2013-04-02 20:51:39
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
