package:
  name: petsc4py
  version: 3.6.0

source:
  fn: petsc4py-3.6.0.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-3.6.0.tar.gz # [linux]
  md5: e63a8e30318b5de9ffb081832e9daf30

build:
  number: 1

requirements:
  build:
    - python {{PY_VER}}*
    - numpy 1.10*
    - petsc
  run:
    - python {{PY_VER}}*
    - numpy 1.10*
    - petsc

test:
  requires:
    - python {{PY_VER}}*
  imports:
    - petsc4py
    - petsc4py.PETSc

about:
  home: https://bitbucket.org/petsc/petsc4py/
  license:  BSD
