{% set name = "petsc4py" %}
{% set version = "3.7.0" %}
{% set sha256 = "e1fda7a68264c3eca2014f253efe4f306fa91d6dab65546764788bd7ad8518c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/{{ name }}-{{ version }}.tar.gz # [not win]
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python {{PY_VER}}*
    - numpy x.x
    - petsc
  run:
    - python {{PY_VER}}*
    - numpy x.x
    - petsc

test:
  requires:
    - python {{PY_VER}}*
  imports:
    - petsc4py
    - petsc4py.PETSc

about:
  home: https://bitbucket.org/petsc/petsc4py/
  license:  BSD
