{% set name = "fda" %}
# Note that conda versions cannot contain -, so any -'s in the version have
# been replaced with _'s.
{% set version = "2.4.4" %}
{% set sha256 = "dc9b26c2a78088474bb7e7983ead8f5928e173e30678cac5cc3cdc98c4cd3b17" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/fda/{{ name }}_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: deSolve, R.matlab, quadprog, nlme, lattice, RCurl, zoo
requirements:
  build:
    - r-base
    - r-matrix

  run:
    - r-base
    - r-matrix

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('fda')" # [not win]
    - "\"%R%\" -e \"library('fda')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.functionaldata.org
  license: GPL (>= 2)
  summary: 'These functions were developed to support functional data analysis as described in
    Ramsay, J. O. and Silverman, B. W. (2005) Functional Data Analysis. New York: Springer.  They
    were ported from earlier versions in Matlab and S-PLUS.  An introduction appears
    in Ramsay, J. O., Hooker, Giles, and Graves, Spencer (2009) Functional Data Analysis
    with R and Matlab (Springer). The package includes data sets and script files working
    many examples including all but one of the 76 figures in this latter book.  Matlab
    versions of the code and sample analyses are no longer distributed through CRAN,
    as they were when the book was published.  For those, ftp from http://www.psych.mcgill.ca/misc/fda/downloads/FDAfuns/
    There you find a set of .zip files containing the functions and sample analyses,
    as well as two .txt files giving instructions for installation and some additional
    information. The changes from Version 2.4.1 are fixes of bugs in density.fd and
    removal of functions create.polynomial.basis, polynompen, and  polynomial. These
    were deleted because the monomial basis does the same thing and because there were
    errors in the code.'

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: fda
# Version: 2.4.4
# Date: 2014.05.03
# Title: Functional Data Analysis
# Author: J. O. Ramsay <ramsay@psych.mcgill.ca>, Hadley Wickham <h.wickham@gmail.com>, Spencer Graves <spencer.graves@prodsyse.com>, Giles Hooker <gjh27@cornell.edu>
# Maintainer: J. O. Ramsay <ramsay@psych.mcgill.ca>
# Depends: R (>= 2.10.0), splines, Matrix, graphics
# Suggests: deSolve, R.matlab, quadprog, nlme, lattice, RCurl, zoo
# Description: These functions were developed to support functional data analysis as described in Ramsay, J. O. and Silverman, B. W. (2005) Functional Data Analysis. New York: Springer.  They were ported from earlier versions in Matlab and S-PLUS.  An introduction appears in Ramsay, J. O., Hooker, Giles, and Graves, Spencer (2009) Functional Data Analysis with R and Matlab (Springer). The package includes data sets and script files working many examples including all but one of the 76 figures in this latter book.  Matlab versions of the code and sample analyses are no longer distributed through CRAN, as they were when the book was published.  For those, ftp from http://www.psych.mcgill.ca/misc/fda/downloads/FDAfuns/ There you find a set of .zip files containing the functions and sample analyses, as well as two .txt files giving instructions for installation and some additional information. The changes from Version 2.4.1 are fixes of bugs in density.fd and removal of functions create.polynomial.basis, polynompen, and  polynomial. These were deleted because the monomial basis does the same thing and because there were errors in the code.
# License: GPL (>= 2)
# URL: http://www.functionaldata.org
# LazyData: true
# Repository: CRAN
# Repository/R-Forge/Project: fda
# Repository/R-Forge/Revision: 761
# Repository/R-Forge/DateTimeStamp: 2014-12-10 23:04:14
# Date/Publication: 2014-12-16 17:59:38
# Packaged: 2014-12-10 23:25:10 UTC; rforge
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
