{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pbs
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.1"

source:
  fn: pbs_1.1.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/pbs_1.1.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/pbs/pbs_1.1.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pbs')" # [not win]
    - "\"%R%\" -e \"library('pbs')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL-2
  summary: Periodic B Splines Basis
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: pbs
# Type: Package
# Imports: graphics, stats, splines
# Title: Periodic B Splines
# Version: 1.1
# Date: 2013-03-22
# Author: Shuangcai Wang
# Maintainer: swang1 <swang1@gmail.com>
# Description: Periodic B Splines Basis
# License: GPL-2
# Packaged: 2013-06-07 19:00:51 UTC; wangs
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-06-08 06:57:39

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
