{% set name = "slepc" %}
{% set version = "3.7.2" %}
{% set sha256 = "09bd88a6023f39aa91edf55f24be1c8b9fdcfebb952539af0292aae69985741f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://slepc.upv.es/download/download.php?filename={{ name }}-{{ version }}.tar.gz # [not win]
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python 2.*  # configure requires python 2
    - petsc
    - mkl-rt 11.1
  run:
    - petsc
    - mkl-rt 11.1

test:
  requires:
    - python 3.4.*  # [py34]
    - python 3.5.*  # [py35]

about:
  home: www.grycap.upv.es/slepc/
  license: GPL3
