package:
  name: slepc
  version: 3.6.0

source:
  fn: slepc-3.6.0.tar.gz
  url: http://slepc.upv.es/download/download.php?filename=slepc-3.6.0.tar.gz # [linux]
  md5: 560a634369fdab3fcaeea35c2cbab6f1

build:
  number: 0
  features:
    - mkl

requirements:
  build:
    - python
    - petsc
    - mkl
  run:
    - petsc
    - mkl

test:
  requires:
    - petsc4py

about:
  home: www.grycap.upv.es/slepc/
  license: GPL3
