package:
  name: slepc
  version: 3.6.0

source:
  fn: slepc-3.6.0.tar.gz
  url: http://slepc.upv.es/download/download.php?filename=slepc-3.6.0.tar.gz # [linux]
  md5: 560a634369fdab3fcaeea35c2cbab6f1

build:
  number: 1

requirements:
  build:
    - python
    - petsc
    - mkl-rt 11.1
  run:
    - petsc
    - mkl-rt 11.1

test:
  requires:
    - python 3.4.*  # [py34]
    - python 3.5.*  # [py35]

about:
  home: www.grycap.upv.es/slepc/
  license: GPL3
