{% set name = "CVXcanon" %}
{% set version = "0.1.1" %}
{% set md5sum = "433a38b55058c5ec1a156a75a7d7308e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5sum }}
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cvxcanon = cvxcanon:main
    #
    # Would create an entry point called cvxcanon that calls cvxcanon.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 5

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy {{ numpy }}
    - scipy
    - {{ compiler('cxx') }}

  run:
    - python {{ python }}
    - numpy {{ numpy }}
    - scipy

test:
  # Python imports
  imports:
    - CVXcanon
  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jacklzhu/CVXcanon
  license: GPLv3
  summary: 'A low-level library to perform the matrix building step in cvxpy, a convex optimization modeling software.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
