{% set version = "2.7.8" %}

package:
  name: rpy2
  version: {{ version }}

source:
  fn: rpy2-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/r/rpy2/rpy2-{{ version }}.tar.gz
  md5: 56ca162bca76bb9c3f935f099c916196
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # This is required to make R link correctly on Linux.
  rpaths:
      - lib/R/lib/
      - lib

  #preserve_egg_dir: True


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - r
    - python
    - setuptools
    - six
    - gcc # [not win]

  run:
    - r
    - python
    - six
    - libgcc # [not win]

test:
  # Python imports
  imports:
    - rpy2
    # these imports fail in lucid tests, but work in lucid  :-/
    #- rpy2.interactive
    #- rpy2.interactive.tests
    #- rpy2.ipython
    #- rpy2.ipython.tests
    - rpy2.rinterface
    #- rpy2.rinterface.tests
    #- rpy2.rlike
    #- rpy2.rlike.tests
    - rpy2.robjects
    #- rpy2.robjects.lib
    #- rpy2.robjects.lib.tests
    #- rpy2.robjects.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
#    - python -m 'rpy2.tests'

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
#    - r-ggplot2 >=2.0

about:
  home: http://rpy.sourceforge.net
  license:  GNU General Public License v2 or later (GPLv2+)
  summary: 'Python interface to the R language (embedded R)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
