{% set name = "scs" %}
{% set version = "1.2.7" %}
{% set sha256 = "e284517e31bd8aac2e1e022376c46bade26d55ce4ef078cf796a9e70ab2b2433" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scs = scs:main
    #
    # Would create an entry point called scs that calls scs.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 5

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy {{ numpy }}
    - scipy >=0.13.2
    - {{ compiler('c') }}

  run:
    - python {{ python }}
    - numpy {{ numpy }}
    - scipy >=0.13.2

test:
  # Python imports
  imports:
    - scs

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/cvxgrp/scs
  license: MIT
  summary: 'scs: splitting conic solver'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
