package:
  name: eigency
  version: "1.74"

source:
  git_url: https://github.com/wouterboomsma/eigency.git
  git_rev: "1.74"
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - eigency = eigency:main
    #
    # Would create an entry point called eigency that calls eigency.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - numpy
    - cython

  run:
    - python
    - numpy
    - cython

test:
  # Python imports
  imports:
    - eigency

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/wouterboomsma/eigency
  license: MIT
  summary: 'Cython interface between the numpy arrays and the Matrix/Array classes of the Eigen C++ library'
  license_file: LICENSE.txt

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
