{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-magic
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.5_6"

source:
  fn: magic_1.5-6.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/magic_1.5-6.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/magic/magic_1.5-6.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-abind

  run:
    - r-base
    - r-abind

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('magic')" # [not win]
    - "\"%R%\" -e \"library('magic')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL-2
  summary: a collection of efficient, vectorized algorithms for the creation and investigation
    of magic squares and hypercubes, including a variety of functions for the manipulation
    and analysis of arbitrarily dimensioned arrays.  The package includes methods for
    creating normal magic squares of any order greater than 2.  The ultimate intention
    is for the package to be a computerized embodiment all magic square knowledge, including
    direct numerical verification of properties of magic squares (such as recent results
    on the determinant of odd-ordered semimagic squares).  Some antimagic functionality
    is included.  The package also serves as a rebuttal to the often-heard comment "I
    thought R was just for statistics".
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: magic
# Version: 1.5-6
# Date: 3 July 2012
# Title: create and investigate magic squares
# Author: Robin K. S. Hankin
# Depends: R (>= 2.10), abind
# Description: a collection of efficient, vectorized algorithms for the creation and investigation of magic squares and hypercubes, including a variety of functions for the manipulation and analysis of arbitrarily dimensioned arrays.  The package includes methods for creating normal magic squares of any order greater than 2.  The ultimate intention is for the package to be a computerized embodiment all magic square knowledge, including direct numerical verification of properties of magic squares (such as recent results on the determinant of odd-ordered semimagic squares).  Some antimagic functionality is included.  The package also serves as a rebuttal to the often-heard comment "I thought R was just for statistics".
# Maintainer: "Robin K. S. Hankin" <hankin.robin@gmail.com>
# License: GPL-2
# Packaged: 2013-11-19 19:55:40 UTC; rhankin
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-11-20 00:55:43

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
