package:
  name: ecos
  version: "2.0.4"

source:
  fn: ecos-2.0.4.tar.gz
  url: https://files.pythonhosted.org/packages/77/09/a310016980c7652e6470d5bf4938d792b5c99528b16d5c20ca5e3e377bf0/ecos-2.0.4.tar.gz
  md5: 39cc4c4a5598cc51ca4dc9aec810f41a
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ecos = ecos:main
    #
    # Would create an entry point called ecos that calls ecos.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6
    - scipy >=0.9
    - gcc

  run:
    - python
    - numpy >=1.6
    - scipy >=0.9

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/embotech/ecos
  license: GPLv3
  summary: 'This is the Python package for ECOS: Embedded Cone Solver. See Github page for more information.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
