{% set name = 'arules' %}
{% set version = '1.5-0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz

  sha256: b1daba30c2fb73c363c2864f3f0f6453d1f0d6b71c6631ef9c115aacd47be574
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: pmml, XML, arulesViz, testthat
requirements:
  build:
    - r-base
    - r-matrix >=1.2_0
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-matrix >=1.2_0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('arules')"  # [not win]
    - "\"%R%\" -e \"library('arules')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://mhahsler.github.io/arules/, http://lyle.smu.edu/IDA/arules
  license: GPL-3
  summary: Provides the infrastructure for representing, manipulating and analyzing transaction
    data and patterns (frequent itemsets and association rules). Also provides interfaces
    to C implementations of the association mining algorithms Apriori and Eclat by C.
    Borgelt.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: arules
# Version: 1.5-2
# Date: 2017-03-12
# Title: Mining Association Rules and Frequent Itemsets
# Authors@R: c(person("Michael", "Hahsler", role = c("aut", "cre", "cph"), email = "mhahsler@lyle.smu.edu"), person("Christian", "Buchta", role = c("aut", "cph")), person("Bettina", "Gruen", role = c("aut", "cph")), person("Kurt", "Hornik", role = c("aut", "cph")), person("Ian", "Johnson", role = c("ctb", "cph")), person("Christian", "Borgelt", role = c("ctb", "cph")))
# Description: Provides the infrastructure for representing, manipulating and analyzing transaction data and patterns (frequent itemsets and association rules). Also provides interfaces to C implementations of the association mining algorithms Apriori and Eclat by C. Borgelt.
# Classification/ACM: G.4, H.2.8, I.5.1
# URL: http://mhahsler.github.io/arules/, http://lyle.smu.edu/IDA/arules
# BugReports: https://github.com/mhahsler/arules
# Depends: R (>= 3.3.2), Matrix (>= 1.2-0)
# Imports: stats, methods, graphics, utils
# Suggests: pmml, XML, arulesViz, testthat
# License: GPL-3
# Copyright: The code for apriori and eclat in src/rapriori.c was obtained from http://www.borgelt.net/ and is Copyright (C) 1996-2003 Christian Borgelt. All other code is Copyright (C) Michael Hahsler, Christian Buchta, Bettina Gruen and Kurt Hornik.
# NeedsCompilation: yes
# Packaged: 2017-03-12 21:17:38 UTC; hahsler
# Author: Michael Hahsler [aut, cre, cph], Christian Buchta [aut, cph], Bettina Gruen [aut, cph], Kurt Hornik [aut, cph], Ian Johnson [ctb, cph], Christian Borgelt [ctb, cph]
# Maintainer: Michael Hahsler <mhahsler@lyle.smu.edu>
# Repository: CRAN
# Date/Publication: 2017-03-13 00:19:08

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
