package:
  name: r-randomforestsrc
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.6.1"

source:
  fn: randomForestSRC_1.6.1.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/Archive/randomForestSRC/randomForestSRC_1.6.1.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  md5: 743092091fc75863075e0dbe602f83bb
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: glmnet, XML, survival, pec, prodlim, Hmisc, mlbench
requirements:
  build:
    - r
    - gcc # [not win]

  run:
    - r
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('randomForestSRC')" # [not win]
    - "\"%R%\" -e \"library('randomForestSRC')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://web.ccs.miami.edu/~hishwaran http://www.kogalur.com
  license: GPL (>= 3)
  summary: A unified treatment of Breiman's random forests for survival, regression and classification
    problems based on Ishwaran and Kogalur's random survival forests (RSF) package.  The
    package runs in both serial and parallel (OpenMP) modes. Now extended to include
    multivariate and unsupervised forests.

# The original CRAN metadata for this package was:

# Package: randomForestSRC
# Version: 2.0.7
# Date: 2016-01-15
# Title: Random Forests for Survival, Regression and Classification (RF-SRC)
# Author: Hemant Ishwaran <hemant.ishwaran@gmail.com>, Udaya B. Kogalur <ubk@kogalur.com>
# Maintainer: Udaya B. Kogalur <ubk@kogalur.com>
# Depends: R (>= 3.1.0), parallel
# Suggests: glmnet, XML, survival, pec, prodlim, Hmisc, mlbench
# Description: A unified treatment of Breiman's random forests for survival, regression and classification problems based on Ishwaran and Kogalur's random survival forests (RSF) package.  The package runs in both serial and parallel (OpenMP) modes. Now extended to include multivariate and unsupervised forests.
# License: GPL (>= 3)
# URL: http://web.ccs.miami.edu/~hishwaran http://www.kogalur.com
# NeedsCompilation: yes
# Packaged: 2016-01-15 18:08:17 UTC; kogalur
# Repository: CRAN
# Date/Publication: 2016-01-15 19:45:20

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
