{% set name = "thriftpy" %}
{% set version = "0.3.9" %}
{% set sha256 = "309e57d97b5bfa01601393ad4f245451e989d6206a59279e56866b264a99796d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - setuptools
    - ply >=3.4,<4.0
    - cython # [not win]

  run:
    - python
    - ply >=3.4,<4.0
    - cython

test:
  # Python imports
  imports:
    - thriftpy
    - thriftpy.contrib
    - thriftpy.contrib.tracking
    - thriftpy.parser
    - thriftpy.protocol
    - thriftpy.protocol.cybin  # [not win]    
    - thriftpy.transport
    - thriftpy.transport.buffered
    - thriftpy.transport.framed
    - thriftpy.transport.memory

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    #- tornado >=4.0,<5.0
    #- toro ==0.6
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://thriftpy.readthedocs.org/
  license: MIT License
  summary: 'Pure python implementation of Apache Thrift.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
