package:
  name: cvxpy
  version: "0.4.2"

source:
  fn: cvxpy-0.4.2.tar.gz
  url: https://files.pythonhosted.org/packages/e7/0b/b5d08d419314fb5f79628ec11c3615e9e93423f4980cde8046a74044b223/cvxpy-0.4.2.tar.gz
  md5: 2c418ceb2e26acbf50ab6929af6aa8e4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cvxpy = cvxpy:main
    #
    # Would create an entry point called cvxpy that calls cvxpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - cvxopt >=1.1.6
    - ecos >=2
    - scs >=1.1.3
    - multiprocess
    - fastcache
    - six
    - toolz
    - numpy >=1.9
    - scipy >=0.15
    - cvxcanon >=0.0.22

  run:
    - python
    - cvxopt >=1.1.6
    - ecos >=2
    - scs >=1.1.3
    - multiprocess
    - fastcache
    - six
    - toolz
    - numpy >=1.9
    - scipy >=0.15
    - cvxcanon >=0.0.22

test:
  # Python imports
  imports:
    - cvxpy
    - cvxpy.atoms
    - cvxpy.atoms.affine
    - cvxpy.atoms.elementwise
    - cvxpy.constraints
    - cvxpy.expressions
    - cvxpy.expressions.constants
    - cvxpy.expressions.variables
    - cvxpy.interface
    - cvxpy.interface.cvxopt_interface
    - cvxpy.interface.numpy_interface
    - cvxpy.lin_ops
    - cvxpy.problems
    - cvxpy.problems.problem_data
    - cvxpy.problems.solvers
    - cvxpy.tests
    - cvxpy.transforms
    - cvxpy.utilities

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/cvxgrp/cvxpy/
  license: GPLv3
  summary: 'A domain-specific language for modeling convex optimization problems in Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
